<?php

/**
 * @file
 * Module for the Things Entity - a starting point to create your own Entity
 * and associated administration interface
 */  

/**
 * Implementation of hook_menu().
 */
function thing_menu() {

  $items = array();

  $items['admin/drupal-of-things/configuration/settings'] = array(
    'title' => 'Settings',
    'description' => 'Settings for Drupal of Things',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('thing_admin'),
    'access arguments' => array('administer thing settings'),
    'weight' => 20,
    'type' => MENU_NORMAL_ITEM,
   );

  $items['admin/drupal-of-things/configuration'] = array(
    'title' => 'Configuration',
    'description' => 'Settings related to Drupal of Things.',
    'position' => 'left',
    'weight' => 20,
    'page callback' => 'thing_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
  );

  $items['admin/drupal-of-things'] = array(
    'title' => 'Drupal of Things',
    'description' => 'Drupal of Things main page.',
    'position' => 'left',
    'weight' => -20,
    'page callback' => 'thing_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
  );

  return $items;
}

/**
 * Implements hook_menu_alter(). Move GCM settings into drupal-of-things.
 */
function thing_menu_alter(&$items) {
  $gcm_settings = $items['admin/config/workflow/gcm/settings'];
  unset($items['admin/config/workflow/gcm/settings']);
  $items['admin/drupal-of-things/configuration/gcm'] = $gcm_settings;
}

/**
 * Provide a single block from the administration menu as a page.
 *
 * This function is often a destination for these blocks.
 * For example, 'admin/structure/types' needs to have a destination to be valid
 * in the Drupal menu system, but too much information there might be
 * hidden, so we supply the contents of the block.
 *
 * @return
 *   The output HTML.
 */
function thing_admin_menu_block_page() {
  $item = menu_get_item();
  if ($content = system_admin_menu_block($item)) {
    $output = theme('admin_block_content', array('content' => $content));
  }
  else {
    $output = t('You do not have any administrative items.');
  }
  return $output;
}

function thing_admin() {
  $form = array();

  $form['thing_users_role'] = array(
    '#type' => 'textfield',
    '#title' => t('Things role'),
    '#default_value' => variable_get('thing_users_role', '0'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/*
 * Implementation of hook_hook_info
 */
function thing_hook_info() {
  $hooks['thing_create'] = array(
    'group' => 'thing',
  );
  $hooks['thing_update'] = array(
    'group' => 'thing',
  );
  $hooks['thing_delete'] = array(
    'group' => 'thing',
  );
  $hooks['thing_load'] = array(
    'group' => 'thing',
  );
  $hooks['thing_save'] = array(
    'group' => 'thing',
  );
  return $hooks;
}

/**
 * Implement hook_entity_info().
 *
 * We define two entities here - the actual entity that will hold our domain
 * specific information and an entity that holds information about the different
 * types of entities. See here: http://drupal.org/node/977380 for a discussion on this
 * choice.
 */
function thing_entity_info() {
  $return['thing'] = array(
    'label' => t('Thing'),
    // The entity class and controller class extend the classes provided by the
    // Entity API
    'entity class' => 'Thing',
    'controller class' => 'ThingsController',
    'base table' => 'thing',
    'fieldable' => TRUE,
    'entity keys' => array(
        'id' => 'thing_id',
        'bundle' => 'type',
    ),
    // Bundles are defined by the thing types below
    'bundles' => array(),
    // Bundle keys tell the FieldAPI how to extract information from the bundle objects
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'creation callback' => 'thing_create',
    'access callback' => 'thing_access',
    'module' => 'thing',
    // The information below is used by the ThingsUIController (which extends the EntityDefaultUIController)
    'admin ui' => array(
      'path' => 'admin/drupal-of-things/thing',
      'file' => 'thing.admin.inc',
      'controller class' => 'ThingsUIController',
      'menu wildcard' => '%thing',
    ),
  );
  // The entity that holds information about the entity types	  
  $return['thing_type'] = array(
    'label' => t('Things Type'),
    'entity class' => 'ThingsType',
    'controller class' => 'ThingsTypeController',
    'base table' => 'thing_type',
    'fieldable' => FALSE,
    'bundle of' => 'thing',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'thing_type_access',
    'module' => 'thing',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/drupal-of-things/configuration/thing-types',
      'file' => 'thing_type.admin.inc',
      'controller class' => 'ThingsTypeUIController',
    ),
  );

  return $return;
}


/**
 * Implements hook_entity_info_alter().
 *
 * We are adding the info about the thing types via a hook to avoid a recursion
 * issue as loading the thing types requires the entity info as well.
 *
 * @todo This needs to be improved
 */
function thing_entity_info_alter(&$entity_info) {
  foreach (thing_get_types() as $type => $info) {
    $entity_info['thing']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/drupal-of-things/configuration/thing-types/manage/%thing_type',
        'real path' => 'admin/drupal-of-things/configuration/thing-types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer thing types'),
      ),
    );
  }
}
  

/**
 * Implements hook_permission().
 */
function thing_permission() {
  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity
  $permissions = array(
    'administer thing types' => array(
      'title' => t('Administer thing types'),
      'description' => t('Create and delete fields for thing types, and set their permissions.'),
    ),
    'administer thing' => array(
      'title' => t('Administer thing'),
      'description' => t('Edit and delete all thing'),
    ),  
    'administer thing settings' => array(
      'title' => t('Administer Drupal of Things settings'),
    ),
  );
  
  //Generate permissions per thing
  foreach (thing_get_types() as $type) {
    $type_name = check_plain($type->type);
    $permissions += array(
      "edit any $type_name thing" => array(
        'title' => t('%type_name: Edit any thing', array('%type_name' => $type->label)),
      ),
      "view any $type_name thing" => array(
        'title' => t('%type_name: View any thing', array('%type_name' => $type->label)),
      ),
    );
  }
  return $permissions;  
}


/**
 * Determines whether the given user has access to a thing.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $thing
 *   Optionally a thing or a thing type to check access for. If nothing is
 *   given, access for all thing is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function thing_access($op, $thing = NULL, $account = NULL) {
  if (user_access('administer thing', $account)) {
    return TRUE;
  }
  if (isset($thing) && $type_name = thing->type) {
    $op = ($op == 'view') ? 'view' : 'edit';
    if (user_access("$op any $type_name thing", $account)) {
      return TRUE;
    }
  }
  return FALSE;
}


/**
 * Access callback for the entity API.
 */
function thing_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer thing types', $account);
}


/**
 * Gets an array of all thing types, keyed by the type name.
 *
 * @param $type_name
 *   If set, the type with the given name is returned.
 * @return ThingsType[]
 *   Depending whether $type isset, an array of thing types or a single one.
 */
function thing_get_types($type_name = NULL) {
  // entity_load will get the Entity controller for our thing entity and call the load
  // function of that object - we are loading entities by name here.
  $types = entity_load_multiple_by_name('thing_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}


/**
 * Menu argument loader; Load a thing type by string.
 *
 * @param $type
 *   The machine-readable name of a thing type to load.
 * @return
 *   A thing type array or FALSE if $type does not exist.
 */
function thing_type_load($type) {
  return thing_get_types($type);
}


/**
 * Fetch a thing object. Make sure that the wildcard you choose
 * in the thing entity definition fits the function name here.
 *
 * @param $thing_id
 *   Integer specifying the thing id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $thing object or FALSE if it cannot be loaded.
 *
 * @see thing_load_multiple()
 */
function thing_load($thing_id, $reset = FALSE) {
  $thing = thing_load_multiple(array($thing_id), array(), $reset);
  module_invoke_all('thing_load', $thing_id, reset($thing));
  return reset($thing);
}


/**
 * Load multiple thing based on certain conditions.
 *
 * @param $thing_ids
 *   An array of thing IDs.
 * @param $conditions
 *   An array of conditions to match against the {thing} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of thing objects, indexed by thing_id.
 *
 * @see entity_load()
 * @see thing_load()
 */
function thing_load_multiple($thing_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('thing', $thing_ids, $conditions, $reset);
}


/**
 * Deletes a thing.
 */
function thing_delete(Things $thing) {
  module_invoke_all('thing_delete', $thing);

  $thing->delete();
}


/**
 * Delete multiple thing.
 *
 * @param $thing_ids
 *   An array of thing IDs.
 */
function thing_delete_multiple(array $thing_ids) {
  entity_get_controller('thing')->delete($thing_ids);
}


/**
 * Create a thing object.
 */
function thing_create($values = array()) {
  $thing = entity_get_controller('thing')->create($values);
  module_invoke_all('thing_create', $thing);
  return $thing;
}


/**
 * Saves a thing to the database.
 *
 * @param $thing
 *   The thing object.
 */
function thing_save(Things $thing) {
  module_invoke_all('thing_save', $thing);

  return $thing->save();
}


/**
 * Saves a thing type to the db.
 */
function thing_type_save(ThingsType $type) {
  $type->save();
}


/**
 * Deletes a thing type from the db.
 */
function thing_type_delete(ThingsType $type) {
  $type->delete();
}


/**
 * URI callback for thing
 */
function thing_uri(Things $thing){
  return array(
    'path' => 'thing/' . $thing->thing_id,
  );
}


/**
 * Menu title callback for showing individual entities
 */
function thing_page_title(Things $thing){
  return $thing->name;
}


/**
 * Sets up content to show an individual thing
 * @todo - get rid of drupal_set_title();
 */
function thing_page_view($thing, $view_mode = 'full') {
  $controller = entity_get_controller('thing');
  $content = $controller->view(array($thing->thing_id => $thing));
  drupal_set_title($thing->name);
  return $content;
}


/**
 * Implements hook_views_api().
 */
function thing_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'thing') . '/views',
  );
}


/**
 * Implement hook_theme().
 */
function thing_theme() {
  return array(
    'thing_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'thing.admin.inc',
    ),
    'thing' => array(
      'render element' => 'elements',
      'template' => 'thing',
    ),
  );
}  


/**
 * Implements hook_menu_local_tasks_alter().
 */
function thing_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/drupal-of-things/configuration/thing/add' on 'admin/structure/thing'.
  if ($root_path == 'admin/drupal-of-things/thing') {
    $item = menu_get_item('admin/drupal-of-things/thing/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}


/**
 * The class used for thing entities
 */
class Things extends Entity {
  
  public function __construct($values = array()) {
    parent::__construct($values, 'thing');
  }

  protected function defaultLabel() {
    return $this->name;
  }

  protected function defaultUri() {
    return array('path' => 'thing/' . $this->thing_id);
  }
  
  
}


/**
 * The class used for thing type entities
 */
class ThingsType extends Entity {
  
  public $type;
  public $label;
  
  public function __construct($values = array()) {
    parent::__construct($values, 'thing_type');
  }
  
}


/**
 * The Controller for Things entities
 */
class ThingsController extends EntityAPIController {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }


  /**
   * Create a thing - we first set up the values that are specific
   * to our thing schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the thing.
   *
   * @return
   *   A thing object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our Things
    $values += array( 
      'thing_id' => '',
      'is_new' => TRUE,
      'title' => '',
      'created' => '',
      'changed' => '',
      'data' => '',
    );
    
    $thing = parent::create($values);
    return $thing;
  }
}


/**
 * The Controller for Things entities
 */
class ThingsTypeController extends EntityAPIControllerExportable {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }
  
   /**
   * Create a thing type - we first set up the values that are specific
   * to our thing type schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the thing.
   *
   * @return
   *   A thing type object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our Things
    $values += array( 
      'id' => '',
      'is_new' => TRUE,
      'data' => '',
    );
    $thing_type = parent::create($values);
    return $thing_type;
  }

}
